Create parent loggers upon initialization
scala-js/scala-js-java-logging pull request #10
Opened 2017-03-19 07:56 UTC by xerial

This PR:
 - [X] Removes fixParent, which happens to create multiple root loggers with the empty name `""`
 - [X] Instead added `prepareParentLoggerOf(name)` to ensure create and register parent loggers in advance. This also reduces the overhead of resolving parent loggers

2017-03-19 08:06 UTC, sjrd commented
Could we have appropriate tests for this PR?

2017-03-19 14:22 UTC, xerial commented
@sjrd OK. I'll add test cases

2017-03-19 15:11 UTC, xerial commented
@sjrd Added test cases.  
- test_single_root fails in the current master branch
- Fixed to use the root logger for the parent of the anonymous logger

2017-03-19 15:19 UTC, xerial commented
I'll check test failures at Travis

2017-03-19 17:22 UTC, xerial commented
@sjrd Changed the design to be compatible with Scala JVM/JS. 
- The parent logger is resolved at newLogger creation. The parent will be an already existing parent or ancestor (including root). 
- All child loggers will be updated if a new parent logger is added. 
- The root and global logger are now registered at Logger object initialization time.

2017-03-20 18:11 UTC, xerial commented
@sjrd Could you review this PR again? Actually this is a blocker for supporting Scala.js in our projects: https://github.com/wvlet/log/pull/8, https://github.com/wvlet/airframe/pull/45, etc.

Thanks in advance.

2017-03-21 16:10 UTC, sjrd requested changes

2017-03-21 16:10 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/logging/LoggerTest.scala
> +    val loggerName = s"${prefix}.a.b.c.d}"
The second `}` shouldn't be there. It was a little bit confusing for a second.

2017-03-21 16:10 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/logging/LoggerTest.scala
> +      case other => findRoot(l.getParent)
Vertically align the `=>`'s in a pattern matching with one-liner cases. It's the only thing we vertically align.

2017-03-21 16:10 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/logging/LoggerTest.scala
> +    def findRoot(l:Logger): Logger = l.getParent match {
Missing space after the `:`

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +  private val ROOT_LOGGER_NAME: String = ""
Actually both of these should be `final val`s without the explicit type `: String`. (`private final val` for `ROOT_LOGGER_NAME`). While you're here, could you also remove the duplicate space between `=` and `"global"`?

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +  private lazy val loggers: mutable.Map[String, Logger] = mutable.Map.empty
I see no reason for this to be `lazy`. It will only make it slower.

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +    */
This comment fits on a single line:
```scala
/** Find parent logger. */
```
(see also https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#scaladoc)

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +  private def findParentLoggerOf(name:String): Logger = {
Missing space after `:`

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +        val parentName = parentNodes.mkString(".")
That's some expensive way to compute the parent name. Consider:
```scala
val parentName = name.substring(0, name.lastIndexOf('.').max(0))
```

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +            findParentLoggerOf(parentName)
Keep the `None` case on one line and vertically align the `=>`s.

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +  private def updateChildLoggerParent(newParent:Logger): Unit ={
Missing space after `:` and before `{`.

2017-03-21 16:10 UTC, sjrd commented on src/main/scala/java/util/logging/Logger.scala
> +      }
I'm confused here. I don't really understand the comment, and I also don't understand how the condition of the `if` reflects what is described by the comment. Could you elaborate, please?

2017-03-21 20:24 UTC, xerial commented
@sjrd Thanks for the review and applied the review comment. And also added more comments to `updateChildLoggerParent` to make clear its behavior.

2017-03-21 20:36 UTC, sjrd approved these changes

2017-03-21 20:38 UTC, merged